# username & db postgres
version: '3.1'

services:

  redis:
    image: redis
    ports:
    - "6379:6379"

  db:
    image: postgres
    restart: always
    ports:
      - 1234:5432
    environment:
      POSTGRES_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080